// 第四幕装备规划器演示数据：取自 yl-editor equipment.expand.data.json 全量真实条目
// 弓（Bows）25 条按需求等级降序；胸甲（Body_Armours）按 7 个防御组分组、组内按属性和降序
// 图标走 edit.filtereditor.cn 在线直链（加载失败由组件自动隐藏）

export interface BowItem {
    label: string
    value: string
    icon: string
    level: number
    pd: string
    aps: string
    crit: string
}

export interface ArmourItem {
    label: string
    value: string
    icon: string
    group: number // 防御组下标（0 纯护甲 / 1 纯闪避 / 2 纯护盾 / 3 闪避&护盾 / 4 护甲&闪避 / 5 护甲&护盾 / 6 三重）
    sortVal: number // 组内排序值（单属性值或属性和）
}

export const bows: BowItem[] = [
    { label: "狂热之弓", value: "Fanatic Bow", icon: "/images/equipment/f843cfccda9f.webp", level: 79, pd: "47-79", aps: "1.2", crit: "5%" },
    { label: "双子之弓", value: "Gemini Bow", icon: "/images/equipment/585e58a7699c.webp", level: 78, pd: "39-72", aps: "1.15", crit: "5%" },
    { label: "毁灭者之弓", value: "Obliterator Bow", icon: "/images/equipment/0c69034ac99e.webp", level: 78, pd: "62-115", aps: "1.1", crit: "5%" },
    { label: "守护者之弓", value: "Guardian Bow", icon: "/images/equipment/92d0c522df32.webp", level: 77, pd: "53-88", aps: "1.15", crit: "5%" },
    { label: "寻战之弓", value: "Warmonger Bow", icon: "/images/equipment/3bdefe2b7600.webp", level: 77, pd: "56-84", aps: "1.2", crit: "5%" },
    { label: "骑兵之弓", value: "Cavalry Bow", icon: "/images/equipment/8bd2b525e13d.webp", level: 72, pd: "49-82", aps: "1.2", crit: "5%" },
    { label: "铁木短弓", value: "Ironwood Shortbow", icon: "/images/equipment/32bc4924c37b.webp", level: 67, pd: "41-76", aps: "1.25", crit: "5%" },
    { label: "心木短弓", value: "Heartwood Shortbow", icon: "/images/equipment/32bc4924c37b.webp", level: 67, pd: "41-76", aps: "1.25", crit: "5%" },
    { label: "重装强弓", value: "Heavy Bow", icon: "/images/equipment/95deb4bf474e.webp", level: 65, pd: "45-75", aps: "1.2", crit: "5%" },
    { label: "军用战弓", value: "Militant Bow", icon: "/images/equipment/3bdefe2b7600.webp", level: 62, pd: "46-69", aps: "1.2", crit: "5%" },
    { label: "联排之弓", value: "Adherent Bow", icon: "/images/equipment/f843cfccda9f.webp", level: 59, pd: "35-59", aps: "1.2", crit: "5%" },
    { label: "双生之弓", value: "Twin Bow", icon: "/images/equipment/585e58a7699c.webp", level: 54, pd: "32-60", aps: "1.15", crit: "5%" },
    { label: "骑射之弓", value: "Rider Bow", icon: "/images/equipment/8bd2b525e13d.webp", level: 51, pd: "36-61", aps: "1.2", crit: "5%" },
    { label: "部族弓", value: "Tribal Bow", icon: "/images/equipment/f6fbd5863308.webp", level: 50, pd: "38-57", aps: "1.2", crit: "5%" },
    { label: "保护者之弓", value: "Protector Bow", icon: "/images/equipment/92d0c522df32.webp", level: 48, pd: "35-53", aps: "1.15", crit: "5%" },
    { label: "轰击弓", value: "Artillery Bow", icon: "/images/equipment/0c69034ac99e.webp", level: 45, pd: "39-72", aps: "1.1", crit: "5%" },
    { label: "蛇纹短弓", value: "Snakewood Shortbow", icon: "/images/equipment/32bc4924c37b.webp", level: 45, pd: "29-54", aps: "1.25", crit: "5%" },
    { label: "狂热弓", value: "Zealot Bow", icon: "/images/equipment/3bdefe2b7600.webp", level: 39, pd: "31-47", aps: "1.2", crit: "5%" },
    { label: "教徒弓", value: "Cultist Bow", icon: "/images/equipment/f843cfccda9f.webp", level: 33, pd: "22-36", aps: "1.2", crit: "5%" },
    { label: "双弦弓", value: "Dualstring Bow", icon: "/images/equipment/585e58a7699c.webp", level: 28, pd: "19-35", aps: "1.15", crit: "5%" },
    { label: "复合弓", value: "Composite Bow", icon: "/images/equipment/8bd2b525e13d.webp", level: 22, pd: "19-31", aps: "1.2", crit: "5%" },
    { label: "反曲弓", value: "Recurve Bow", icon: "/images/equipment/4385557daf7d.webp", level: 16, pd: "15-31", aps: "1.1", crit: "5%" },
    { label: "监守弓", value: "Warden Bow", icon: "/images/equipment/92d0c522df32.webp", level: 11, pd: "12-20", aps: "1.15", crit: "5%" },
    { label: "短弓", value: "Shortbow", icon: "/images/equipment/32bc4924c37b.webp", level: 5, pd: "7-14", aps: "1.25", crit: "5%" },
    { label: "粗制弓", value: "Crude Bow", icon: "/images/equipment/e0ea20638792.webp", level: 1, pd: "6-9", aps: "1.2", crit: "5%" },
]

export const armours: ArmourItem[] = [
    { label: "士兵胸甲", value: "Soldier Cuirass", icon: "/images/equipment/7a088dd83414.webp", group: 0, sortVal: 570 },
    { label: "霸王战铠", value: "Conqueror Plate", icon: "/images/equipment/3fe056f94cd7.webp", group: 0, sortVal: 496 },
    { label: "华丽战铠", value: "Ornate Plate", icon: "/images/equipment/2e1a6a6096bb.webp", group: 0, sortVal: 496 },
    { label: "乌扎尔胸甲", value: "Utzaal Cuirass", icon: "/images/equipment/435f61469c5a.webp", group: 0, sortVal: 496 },
    { label: "督军胸甲", value: "Warlord Cuirass", icon: "/images/equipment/836743631e1d.webp", group: 0, sortVal: 496 },
    { label: "石制胸甲", value: "Stone Cuirass", icon: "/images/equipment/435f61469c5a.webp", group: 0, sortVal: 474 },
    { label: "重型战铠", value: "Heavy Plate", icon: "/images/equipment/fc31d2b15dd8.webp", group: 0, sortVal: 453 },
    { label: "冠军胸甲", value: "Champion Cuirass", icon: "/images/equipment/3fe056f94cd7.webp", group: 0, sortVal: 446 },
    { label: "优雅战铠", value: "Elegant Plate", icon: "/images/equipment/2e1a6a6096bb.webp", group: 0, sortVal: 418 },
    { label: "沙誓胸甲", value: "Sandsworn Cuirass", icon: "/images/equipment/36599ec06279.webp", group: 0, sortVal: 397 },
    { label: "酋长胸甲", value: "Chieftain Cuirass", icon: "/images/equipment/836743631e1d.webp", group: 0, sortVal: 390 },
    { label: "粗糙胸甲", value: "Rugged Cuirass", icon: "/images/equipment/7a088dd83414.webp", group: 0, sortVal: 376 },
    { label: "巨灵之铠", value: "Juggernaut Plate", icon: "/images/equipment/d81b41fb82d3.webp", group: 0, sortVal: 355 },
    { label: "野蛮人战铠", value: "Barbarian Plate", icon: "/images/equipment/e9de3c261ddb.webp", group: 0, sortVal: 355 },
    { label: "瓦尔胸甲", value: "Vaal Cuirass", icon: "/images/equipment/435f61469c5a.webp", group: 0, sortVal: 298 },
    { label: "连身铠甲", value: "Full Plate", icon: "/images/equipment/fc31d2b15dd8.webp", group: 0, sortVal: 270 },
    { label: "冷钢之铠", value: "Steel Plate", icon: "/images/equipment/2e1a6a6096bb.webp", group: 0, sortVal: 228 },
    { label: "马拉克斯胸甲", value: "Maraketh Cuirass", icon: "/images/equipment/36599ec06279.webp", group: 0, sortVal: 178 },
    { label: "劫掠之铠", value: "Raider Plate", icon: "/images/equipment/c313f95afcd9.webp", group: 0, sortVal: 150 },
    { label: "铁锻胸甲", value: "Iron Cuirass", icon: "/images/equipment/7a088dd83414.webp", group: 0, sortVal: 115 },
    { label: "覆皮之铠", value: "Fur Plate", icon: "/images/equipment/e9de3c261ddb.webp", group: 0, sortVal: 66 },
    { label: "锈蚀胸甲", value: "Rusted Cuirass", icon: "/images/equipment/3fe056f94cd7.webp", group: 0, sortVal: 45 },
    { label: "滑击背心", value: "Slipstrike Vest", icon: "/images/equipment/c5648f4d690f.webp", group: 1, sortVal: 519 },
    { label: "浮华背心", value: "Exquisite Vest", icon: "/images/equipment/49ab8a8c1a8a.webp", group: 1, sortVal: 451 },
    { label: "铠装背心", value: "Armoured Vest", icon: "/images/equipment/d6e6e054cfd0.webp", group: 1, sortVal: 451 },
    { label: "迅捷潜行者外套", value: "Swiftstalker Coat", icon: "/images/equipment/c87be74c82e3.webp", group: 1, sortVal: 451 },
    { label: "巨龙鳞外套", value: "Wyrmscale Coat", icon: "/images/equipment/05b1a561c84b.webp", group: 1, sortVal: 451 },
    { label: "海盗外套", value: "Corsair Coat", icon: "/images/equipment/56ba39d41388.webp", group: 1, sortVal: 451 },
    { label: "蜥鳞外套", value: "Lizardscale Coat", icon: "/images/equipment/05b1a561c84b.webp", group: 1, sortVal: 432 },
    { label: "跑者背心", value: "Runner Vest", icon: "/images/equipment/df44d3fa165a.webp", group: 1, sortVal: 412 },
    { label: "分层背心", value: "Layered Vest", icon: "/images/equipment/c5648f4d690f.webp", group: 1, sortVal: 379 },
    { label: "疾行者背心", value: "Strider Vest", icon: "/images/equipment/d6e6e054cfd0.webp", group: 1, sortVal: 366 },
    { label: "走私者外套", value: "Smuggler Coat", icon: "/images/equipment/56ba39d41388.webp", group: 1, sortVal: 359 },
    { label: "骑行外套", value: "Riding Coat", icon: "/images/equipment/e218b4c15a32.webp", group: 1, sortVal: 359 },
    { label: "狩猎外套", value: "Hunting Coat", icon: "/images/equipment/c87be74c82e3.webp", group: 1, sortVal: 339 },
    { label: "海贼背心", value: "Corsair Vest", icon: "/images/equipment/9a0b8d4b00e6.webp", group: 1, sortVal: 320 },
    { label: "拼接背心", value: "Patchwork Vest", icon: "/images/equipment/182eea2fb23d.webp", group: 1, sortVal: 320 },
    { label: "蛇鳞外套", value: "Serpentscale Coat", icon: "/images/equipment/05b1a561c84b.webp", group: 1, sortVal: 260 },
    { label: "斥候背心", value: "Scout's Vest", icon: "/images/equipment/df44d3fa165a.webp", group: 1, sortVal: 240 },
    { label: "嵌饰背心", value: "Studded Vest", icon: "/images/equipment/c5648f4d690f.webp", group: 1, sortVal: 194 },
    { label: "恐喙鸟皮外套", value: "Rhoahide Coat", icon: "/images/equipment/e218b4c15a32.webp", group: 1, sortVal: 168 },
    { label: "蔽影背心", value: "Shrouded Vest", icon: "/images/equipment/9983436932c1.webp", group: 1, sortVal: 128 },
    { label: "寻路者外套", value: "Pathfinder Coat", icon: "/images/equipment/c87be74c82e3.webp", group: 1, sortVal: 96 },
    { label: "菱纹背心", value: "Quilted Vest", icon: "/images/equipment/182eea2fb23d.webp", group: 1, sortVal: 49 },
    { label: "皮革背心", value: "Leather Vest", icon: "/images/equipment/d6e6e054cfd0.webp", group: 1, sortVal: 30 },
    { label: "邪恶束衣", value: "Vile Robe", icon: "/images/equipment/de6054d9a732.webp", group: 2, sortVal: 171 },
    { label: "飘逸之衣", value: "Flowing Raiment", icon: "/images/equipment/3d2577ec6603.webp", group: 2, sortVal: 153 },
    { label: "圣礼束衣", value: "Sacramental Robe", icon: "/images/equipment/655c7a4cc462.webp", group: 2, sortVal: 153 },
    { label: "羽饰之衣", value: "Feathered Raiment", icon: "/images/equipment/076d2f9dd1bf.webp", group: 2, sortVal: 153 },
    { label: "劫难之衣", value: "Havoc Raiment", icon: "/images/equipment/ab389235ad2b.webp", group: 2, sortVal: 138 },
    { label: "启迪长袍", value: "Enlightened Robe", icon: "/images/equipment/105b9e99ed64.webp", group: 2, sortVal: 138 },
    { label: "仪式长袍", value: "Ceremonial Robe", icon: "/images/equipment/655c7a4cc462.webp", group: 2, sortVal: 132 },
    { label: "信徒之衣", value: "Adherent's Raiment", icon: "/images/equipment/d4906321e3f0.webp", group: 2, sortVal: 127 },
    { label: "嵌板之衣", value: "Plated Raiment", icon: "/images/equipment/11525b7b53cb.webp", group: 2, sortVal: 126 },
    { label: "河流之衣", value: "River Raiment", icon: "/images/equipment/3d2577ec6603.webp", group: 2, sortVal: 119 },
    { label: "奢华长袍", value: "Luxurious Robe", icon: "/images/equipment/ca6850be0da1.webp", group: 2, sortVal: 114 },
    { label: "密士之衣", value: "Mystic Raiment", icon: "/images/equipment/076d2f9dd1bf.webp", group: 2, sortVal: 110 },
    { label: "诅咒术士长袍", value: "Cursespeaker's Robe", icon: "/images/equipment/de6054d9a732.webp", group: 2, sortVal: 109 },
    { label: "元素使长袍", value: "Elementalist Robe", icon: "/images/equipment/e624cf0324c1.webp", group: 2, sortVal: 103 },
    { label: "飞羽长袍", value: "Avian Robe", icon: "/images/equipment/2fd787aa9271.webp", group: 2, sortVal: 103 },
    { label: "祭坛长袍", value: "Altar Robe", icon: "/images/equipment/655c7a4cc462.webp", group: 2, sortVal: 95 },
    { label: "奉愿之衣", value: "Votive Raiment", icon: "/images/equipment/d4906321e3f0.webp", group: 2, sortVal: 83 },
    { label: "克斯之衣", value: "Keth Raiment", icon: "/images/equipment/3d2577ec6603.webp", group: 2, sortVal: 74 },
    { label: "丝质之袍", value: "Silk Robe", icon: "/images/equipment/ca6850be0da1.webp", group: 2, sortVal: 64 },
    { label: "坠饰之衣", value: "Bone Raiment", icon: "/images/equipment/919a05bdaad7.webp", group: 2, sortVal: 54 },
    { label: "魔蛊长袍", value: "Hexer's Robe", icon: "/images/equipment/de6054d9a732.webp", group: 2, sortVal: 45 },
    { label: "羽饰长袍", value: "Feathered Robe", icon: "/images/equipment/2fd787aa9271.webp", group: 2, sortVal: 35 },
    { label: "破烂长袍", value: "Tattered Robe", icon: "/images/equipment/105b9e99ed64.webp", group: 2, sortVal: 28 },
    { label: "滑布外衣", value: "Sleek Jacket", icon: "/images/equipment/9ae7c325eafe.webp", group: 3, sortVal: 372 },
    { label: "原始印记", value: "Primal Markings", icon: "/images/equipment/ff32a2e20c98.webp", group: 3, sortVal: 350 },
    { label: "暗影束衣", value: "Assassin Garb", icon: "/images/equipment/fc5cac5acc89.webp", group: 3, sortVal: 324 },
    { label: "漫步者外衣", value: "Rambler Jacket", icon: "/images/equipment/3edc77a161f3.webp", group: 3, sortVal: 324 },
    { label: "猎鹰师外衣", value: "Falconer's Jacket", icon: "/images/equipment/5b48603eebcc.webp", group: 3, sortVal: 324 },
    { label: "简朴束衣", value: "Austere Garb", icon: "/images/equipment/ff32a2e20c98.webp", group: 3, sortVal: 324 },
    { label: "小贩外衣", value: "Hawker's Jacket", icon: "/images/equipment/5b48603eebcc.webp", group: 3, sortVal: 310 },
    { label: "哈图纳格斯束衣", value: "Hatungo Garb", icon: "/images/equipment/71da4769db4d.webp", group: 3, sortVal: 296 },
    { label: "流浪外衣", value: "Itinerant Jacket", icon: "/images/equipment/3edc77a161f3.webp", group: 3, sortVal: 273 },
    { label: "苦修束衣", value: "Ascetic Garb", icon: "/images/equipment/ff32a2e20c98.webp", group: 3, sortVal: 260 },
    { label: "传道士束衣", value: "Evangelist Garb", icon: "/images/equipment/b67d86f80243.webp", group: 3, sortVal: 260 },
    { label: "油蜡外衣", value: "Oiled Jacket", icon: "/images/equipment/9ae7c325eafe.webp", group: 3, sortVal: 247 },
    { label: "流贼外衣", value: "Scoundrel Jacket", icon: "/images/equipment/537a51f39e83.webp", group: 3, sortVal: 233 },
    { label: "苦修束衣", value: "Ascetic Garb", icon: "/images/equipment/fc5cac5acc89.webp", group: 3, sortVal: 233 },
    { label: "猎头者外衣", value: "Scalper's Jacket", icon: "/images/equipment/5b48603eebcc.webp", group: 3, sortVal: 205 },
    { label: "隐士束衣", value: "Anchorite Garb", icon: "/images/equipment/71da4769db4d.webp", group: 3, sortVal: 178 },
    { label: "远行者外衣", value: "Wayfarer Jacket", icon: "/images/equipment/3edc77a161f3.webp", group: 3, sortVal: 155 },
    { label: "遁世束衣", value: "Marabout Garb", icon: "/images/equipment/b67d86f80243.webp", group: 3, sortVal: 101 },
    { label: "防水外衣", value: "Waxed Jacket", icon: "/images/equipment/9ae7c325eafe.webp", group: 3, sortVal: 78 },
    { label: "隐士束衣", value: "Anchorite Garb", icon: "/images/equipment/fc5cac5acc89.webp", group: 3, sortVal: 32 },
    { label: "死亡锁甲", value: "Death Mail", icon: "/images/equipment/278d7e934720.webp", group: 4, sortVal: 598 },
    { label: "懦夫护甲", value: "Dastard Armour", icon: "/images/equipment/93ef48cf1c92.webp", group: 4, sortVal: 579 },
    { label: "英武护甲", value: "Heroic Armour", icon: "/images/equipment/6779bdd34858.webp", group: 4, sortVal: 521 },
    { label: "蔽影锁甲", value: "Shrouded Mail", icon: "/images/equipment/9ef5564dbc8e.webp", group: 4, sortVal: 521 },
    { label: "蔽影锁甲", value: "Shrouded Mail", icon: "/images/equipment/9ef5564dbc8e.webp", group: 4, sortVal: 521 },
    { label: "蔽影锁甲", value: "Shrouded Mail", icon: "/images/equipment/9ef5564dbc8e.webp", group: 4, sortVal: 521 },
    { label: "领主锁甲", value: "Thane Mail", icon: "/images/equipment/9328cd3a2758.webp", group: 4, sortVal: 521 },
    { label: "黄金锁甲", value: "Golden Mail", icon: "/images/equipment/278d7e934720.webp", group: 4, sortVal: 498 },
    { label: "开拓者护甲", value: "Trailblazer Armour", icon: "/images/equipment/a88a59da0452.webp", group: 4, sortVal: 475 },
    { label: "斗篷锁甲", value: "Mantled Mail", icon: "/images/equipment/9ef5564dbc8e.webp", group: 4, sortVal: 438 },
    { label: "层叠锁甲", value: "Lamellar Mail", icon: "/images/equipment/6f0e442ddb9f.webp", group: 4, sortVal: 423 },
    { label: "流浪者护甲", value: "Wanderer Armour", icon: "/images/equipment/a394073a196e.webp", group: 4, sortVal: 415 },
    { label: "先祖锁甲", value: "Ancestral Mail", icon: "/images/equipment/9328cd3a2758.webp", group: 4, sortVal: 408 },
    { label: "恶棍护甲", value: "Scoundrel Armour", icon: "/images/equipment/93ef48cf1c92.webp", group: 4, sortVal: 394 },
    { label: "骑士护甲", value: "Knight Armour", icon: "/images/equipment/f93ac591084d.webp", group: 4, sortVal: 371 },
    { label: "锁环甲", value: "Ring Mail", icon: "/images/equipment/6f0e442ddb9f.webp", group: 4, sortVal: 371 },
    { label: "嵌鳞锁甲", value: "Scale Mail", icon: "/images/equipment/278d7e934720.webp", group: 4, sortVal: 311 },
    { label: "探索者护甲", value: "Explorer Armour", icon: "/images/equipment/a88a59da0452.webp", group: 4, sortVal: 281 },
    { label: "披风锁甲", value: "Cloaked Mail", icon: "/images/equipment/9ef5564dbc8e.webp", group: 4, sortVal: 228 },
    { label: "漂泊者护甲", value: "Vagabond Armour", icon: "/images/equipment/a394073a196e.webp", group: 4, sortVal: 154 },
    { label: "盗贼护甲", value: "Rogue Armour", icon: "/images/equipment/93ef48cf1c92.webp", group: 4, sortVal: 116 },
    { label: "环锁甲", value: "Chain Mail", icon: "/images/equipment/6f0e442ddb9f.webp", group: 4, sortVal: 41 },
    { label: "华饰环甲", value: "Ornate Ringmail", icon: "/images/equipment/a9b9591345ce.webp", group: 5, sortVal: 969 },
    { label: "狼皮斗篷", value: "Wolfskin Mantle", icon: "/images/equipment/2f9053ce2f8f.webp", group: 5, sortVal: 400 },
    { label: "崇礼长衣", value: "Revered Vestments", icon: "/images/equipment/29fa1032686f.webp", group: 5, sortVal: 349 },
    { label: "灵鸦斗篷", value: "Corvus Mantle", icon: "/images/equipment/3fdc6bbbc982.webp", group: 5, sortVal: 349 },
    { label: "远古链甲", value: "Ancient Mail", icon: "/images/equipment/a9b9591345ce.webp", group: 5, sortVal: 349 },
    { label: "咒者斗篷", value: "Conjurer Mantle", icon: "/images/equipment/ad2a7fc306a1.webp", group: 5, sortVal: 349 },
    { label: "死亡斗篷", value: "Death Mantle", icon: "/images/equipment/d9abcf879be9.webp", group: 5, sortVal: 349 },
    { label: "海洋风暴斗篷", value: "Seastorm Mantle", icon: "/images/equipment/a3fc97142f3d.webp", group: 5, sortVal: 349 },
    { label: "刻心斗篷", value: "Heartcarver Mantle", icon: "/images/equipment/d9abcf879be9.webp", group: 5, sortVal: 334 },
    { label: "嵌板长衣", value: "Plated Vestments", icon: "/images/equipment/5d1b9ff2b3dc.webp", group: 5, sortVal: 319 },
    { label: "秘术家斗篷", value: "Occultist Mantle", icon: "/images/equipment/ad2a7fc306a1.webp", group: 5, sortVal: 295 },
    { label: "鎏金长衣", value: "Gilded Vestments", icon: "/images/equipment/b5a76d651852.webp", group: 5, sortVal: 285 },
    { label: "潮贤斗篷", value: "Tideseer Mantle", icon: "/images/equipment/a3fc97142f3d.webp", group: 5, sortVal: 281 },
    { label: "链甲长衣", value: "Chain Vestments", icon: "/images/equipment/3de88abb7121.webp", group: 5, sortVal: 281 },
    { label: "熊皮斗篷", value: "Bearskin Mantle", icon: "/images/equipment/2f9053ce2f8f.webp", group: 5, sortVal: 267 },
    { label: "圣徒长衣", value: "Cleric Vestments", icon: "/images/equipment/a85e42c43b0c.webp", group: 5, sortVal: 252 },
    { label: "圣堂武僧长衣", value: "Templar Vestments", icon: "/images/equipment/72062c605459.webp", group: 5, sortVal: 252 },
    { label: "献祭斗篷", value: "Sacrificial Mantle", icon: "/images/equipment/d9abcf879be9.webp", group: 5, sortVal: 208 },
    { label: "武装长衣", value: "Ironclad Vestments", icon: "/images/equipment/5d1b9ff2b3dc.webp", group: 5, sortVal: 195 },
    { label: "萨满斗篷", value: "Shaman Mantle", icon: "/images/equipment/ad2a7fc306a1.webp", group: 5, sortVal: 170 },
    { label: "锁子长衣", value: "Mail Vestments", icon: "/images/equipment/3de88abb7121.webp", group: 5, sortVal: 113 },
    { label: "毛皮斗篷", value: "Pelt Mantle", icon: "/images/equipment/2f9053ce2f8f.webp", group: 5, sortVal: 83 },
    { label: "朝圣者长衣", value: "Pilgrim Vestments", icon: "/images/equipment/72062c605459.webp", group: 5, sortVal: 41 },
    { label: "献祭盛装", value: "Sacrificial Regalia", icon: "/images/equipment/b30b395f05b6.webp", group: 6, sortVal: 597 },
    { label: "恢弘盛装", value: "Grand Regalia", icon: "/images/equipment/3fe056f94cd7.webp", group: 6, sortVal: 397 },
    { label: "贪婪锁甲", value: "Grasping Mail", icon: "/images/equipment/e032278e0efa.webp", group: 6, sortVal: 397 },
]
